# Data Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: ~
LABEL_FIELD: label

local_col: # 모델이 실제로 학습할 때 사용하는 특정 컬럼
    inter: [user_id, item_id, label]
    user: [user_id, duration, budget, priority, company_id, category_id]
    item: [item_id, work_exp, price, category_id]
    shared_fields: [category_id]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

# Model settings
model: FM
dataset: FM